services:
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mqtt
    expose:
      - 1883
    ports:
      - 1883:1883
    restart: unless-stopped
    volumes:
      - ./mosquitto/config:/mosquitto/config
